apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: #CHANGE_ME
  region: #CHANGE_ME
  version: "1.21"
vpc:
  id: #CHANGE_ME
  cidr: #CHANGE_ME
  autoAllocateIPv6: false
  subnets:
    private:
      data-access-subnet-1:
        az: #CHANGE_ME
        id: #CHANGE_ME
      data-access-subnet-2:
        az: #CHANGE_ME
        id: #CHANGE_ME
managedNodeGroups:
  - name: ng-1-workers
    instanceTypes: ['t3.medium', 't3.large', 'm5.large']
    spot: true
    labels: {pool: ng-1-workers}
    securityGroups:
      attachIDs: [#CHANGE_ME]
        ssh:
          publicKeyName: #CHANGE_ME
          minSize: 1
          desiredCapacity: 7
          maxSize: 15
          tags:
            'App': 'eks'
            'Name': 'ng-1-workers'
          volumeSize: 15
          privateNetworking: true
          iam:
            withAddonPolicies:
              autoScaler: true
